language: php

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

before_script:
  - composer update

script:
  - composer validate
  - composer style
  - composer test

after_script:
  - vendor/bin/php-coveralls

