language: php

php:
  - 5.4
  - 5.5

before_install:
  - composer self-update

before_script:
  - composer update --dev
  - sudo git clone https://github.com/joomla/coding-standards.git `pear config-get php_dir`/PHP/CodeSniffer/Standards/Joomla
  - sudo apt-get install php-codesniffer

script:
  - ant composervalidate
  - ant phpcs
  - ant phpunit

after_script:
  - ant phpdoc

after_success:
  - utility/initiate-publish.sh

env:
  global:
    - secure: "aT8APLDd3qpC9QhrrYt6M/KfTspbuV+75KSQ9V49c6Ga5ErChKvvDlQ7JM0NhNA0NumW5I4A0u0a7QdwuW7xEkDmW0FAtlN0x5XWF2aqh73UalhBDSu2JkQphy2JOM6KX8E49UBRU7X+POdf0Zv2T3XMRIyTyohEIHYZtagTOZA="
